akkadotnet/Akka.Persistence.SqlServer

- build.fsx
- src/.nuget/NuGet.Dev.Config
- src/Akka.Persistence.SqlServer.sln
Used for nightly build integration with changes to Akka.Persistence, Akka.Persistence.TestKit, and Akka.Persistence.Sql.Common
> added the ability to auto-upgrade nuget packages

- .gitignore
- build.cmd
Altered build command to install 4.10
Added .fake/ to .gitignore. Directory contains build artifacts.
> Upgraded FAKE to version 4.1.0

- README.md
This PR adds migration guide section to README.md file for people who previously used this persistent backend in version 1.0.4 and need to migrate their schema up to current version.
> added migration guide from 1.0.4 in readme

- README.md
- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/DbUtils.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerJournalSpec.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerSnapshotStoreSpec.cs
- src/Akka.Persistence.SqlServer.Tests/packages.config
- src/Akka.Persistence.SqlServer.sln
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/Extension.cs
- src/Akka.Persistence.SqlServer/Journal/QueryBuilder.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Snapshot/QueryBuilder.cs
- src/Akka.Persistence.SqlServer/SqlServerInitializer.cs
- src/Akka.Persistence.SqlServer/packages.config
- src/Akka.Persistence.SqlServer/sql-server.conf
- src/NuGet.Config
Notes
- Can't build the package via "build nuget" because it trying to download 1.0.6 packages from nuget
- I have changed here Context to context in order to run tests, otherwise I got an error "Timeout 00:00:03 while waiting for a message of type Akka.Persistence.WriteMessagesSuccessful"
Akka.Persistence.Sql.Common.SqlJournal
```C#
public override Task ReplayMessagesAsync(IActorContext context, string persistenceId, long fromSequenceNr, long toSequenceNr, long max, Action<IPersistentRepresentation> recoveryCallback)
{
return DbEngine.ReplayMessagesAsync(persistenceId, fromSequenceNr, toSequenceNr, max, Context.Sender, recoveryCallback);
}
```
https://github.com/akkadotnet/akka.net/issues/1750
https://github.com/akkadotnet/akka.net/issues/1740 …
> Updated SqlServer plugin to Akka.Persistence 2.4.2

- README.md
- src/Akka.Persistence.SqlServer/Journal/QueryBuilder.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/SqlServerInitializer.cs
What have been done
- Removed unused IsDeleted column
- Change PersistenceID size to NVARCHAR(255) from NVARCHAR(200) (like in JVM implementations)
- Updated Readme (migration from 1.0.4 to 1.0.5 and from 1.0.6 to the latest)
Is it possible to publish nightly builds of this plugin to myget?
> Updated SqlServer plugin to Akka.Persistence 2.4.2 (Part 2)

- README.md
I spent some time in my local environment investigating issue with sql server snapshot and found the issue in the config sample
> added missing hocon plugin configuration

- README.md
- RELEASE_NOTES.md
- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/SqlServerSettingsSpec.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerSnapshotStoreSpec.cs
- src/Akka.Persistence.SqlServer.Tests/packages.config
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/packages.config
- src/Akka.Persistence.SqlServer/sql-server.conf
I've created the issues for two racy spec #41 and #42
Also could close #6, #7, #25, #26, #28, #35
> Akka.Persistence.SqlServer 1.1.0 small fixes

- README.md
- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/app.config
- src/Akka.Persistence.SqlServer.Tests/packages.config
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/packages.config
- src/SharedAssemblyInfo.cs
Updated code to Akka.Persistence v1.1.2 - included ordering column.
> Updated to v1.1.2

- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/app.config
- src/Akka.Persistence.SqlServer.Tests/packages.config
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/packages.config
Packages upgraded, unit tests passing.
> Upgrade akka.net packages to 1.2 stable (issue 64)

- README.md
- src/Akka.Persistence.SqlServer.Tests/AppConfig.xml
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerEventsByPersistenceIdSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerEventsByTagSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerJournalSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerPersistenceIdsSpec.cs
- src/Akka.Persistence.SqlServer/Journal/BatchingSqlServerJournal.cs
Updated to the latest changes. This PR doesn't contain console app I've used previously for benchmarking - I'll attach it as a separate PR.
> Batching journal implementation

- RELEASE_NOTES.md
- build.fsx
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
> v1.3.1 Release Notes

- README.md
Remove beta warning from README
> Remove beta warning from README

- README.md
Was unable to get persistence going using the sample configuration w/1.3.1, found reference to these elsewhere and they seem to be helping.
> include plugin in sample config

- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/AppConfig.xml
- src/Akka.Persistence.SqlServer.Tests/Serialization/SqlServerJournalSerializationSpec.cs
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs
Updated dependencies to Akka.Persistence v1.3.2. Additionally fixed snapshot store problem mentioned in https://github.com/akkadotnet/akka.net/issues/3171
> Updated to v1.3.2

- RELEASE_NOTES.md
Related issue: https://github.com/akkadotnet/akka.net/issues/3171
> Release notes: v1.3.2

- README.md
- RELEASE_NOTES.md
- build.fsx
- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/AppConfig.xml
- src/Akka.Persistence.SqlServer.Tests/Serialization/SqlServerJournalSerializationSpec.cs
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs
Updated to Akka.Persistence v1.3.2. Fixed bug in SnapshotStore query.
> v1.3.2 Release

- .gitignore
- RELEASE_NOTES.md
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
Going to try to get this out ASAP even though Akka.NET v1.3.8 may be rolling live shortly. Meant to do this last week.
> added v1.3.7 release notes

- build.ps1
need to be running NuGet v4.0+ or later to publish this package
> Update to NuGet v4.3.0

- src/Akka.Persistence.SqlServer/Journal/BatchingSqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs
With reference to this issue: https://github.com/akkadotnet/akka.net/issues/4141.
> Constrain input parameters to their field size

- RELEASE_NOTES.md
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerEventsByPersistenceIdSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerEventsByTagSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerJournalSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Batching/BatchingSqlServerPersistenceIdsSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Query/SqlServerAllPersistenceIdsSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Query/SqlServerEventsByPersistenceIdSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Query/SqlServerEventsByTagSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Serialization/SqlServerJournalSerializationSpec.cs
- src/Akka.Persistence.SqlServer.Tests/Serialization/SqlServerSnapshotSerializationSpec.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerJournalSpec.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerSettingsSpec.cs
- src/Akka.Persistence.SqlServer.Tests/SqlServerSnapshotStoreSpec.cs
- src/Akka.Persistence.SqlServer/Extension.cs
- src/Akka.Persistence.SqlServer/Journal/BatchingSqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerSnapshotStore.cs
- src/common.props
* upgraded to Akka.NET v1.4.1-rc3
* updated release notes for v1.4.1-rc3
> V1.4.1 rc3 update (#146)

- RELEASE_NOTES.md
> added v1.4.11 release notes

- src/Akka.Persistence.SqlServer.Tests/SqlServerFixture.cs
> Fix DockerClient.Images.ListImagesAsync(MatchName) does not work

- .gitignore
- src/Akka.Persistence.SqlServer/Helpers/ColumnSizeLoader.cs
- src/Akka.Persistence.SqlServer/Helpers/ColumnSizesInfo.cs
- src/Akka.Persistence.SqlServer/Helpers/JournalColumnSizesInfo.cs
- src/Akka.Persistence.SqlServer/Helpers/SnapshotColumnSizesInfo.cs
- src/Akka.Persistence.SqlServer/Journal/BatchingSqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerSnapshotStore.cs
- src/Akka.Persistence.SqlServer/sql-server.conf
Closes #159
To merge this PR (or even to make it compile) we have to merge this first: https://github.com/akkadotnet/akka.net/pull/4774
Then, once `LoadColumnSizes` base method is supported by `BatchingSqlJournal`, this PR will be ready to go.
- Before fix:
- After fix:
> Load string parameters column sizes to reduce SqlServer query plans count

- src/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj
- src/Akka.Persistence.SqlServer.Tests/DbUtils.cs
- src/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/Akka.Persistence.SqlServer/Journal/BatchingSqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs
- src/Akka.Persistence.SqlServer/Journal/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs
- src/Akka.Persistence.SqlServer/Snapshot/SqlServerSnapshotStore.cs
SqlServer AD Authentication issues #203
> 203 SqlServer Ad Auth

- src/Akka.Persistence.SqlServer.Tests/SqlServerFixture.cs
- SA_PASSWORD changed to MSSQL_SA_PASSWORD.
- Password is missing a special character.
- Log MSSQL docker output in the pipeline log for future debugging
> Fix MSSQL docker environment variables, env names are changed

- RELEASE_NOTES.md
Updated `Release Notes` for Akka.NET 1.4.32
> Version 1.4.32 release notes
